version: '3.8'
services:
  heartbot:
    image: us-central1-docker.pkg.dev/heartbot2/heartbot/heartbot:${TAG}
    container_name: heartbot
    ports:
      - "${PORT}:8042"
    restart: "always"
    environment:
      - AGENT_ID_MODULE1=${AGENT_ID_MODULE1}
      - AGENT_ID_MODULE2=${AGENT_ID_MODULE2}
      - AGENT_ID_MODULE3=${AGENT_ID_MODULE3}
      - AGENT_ID_MODULE4=${AGENT_ID_MODULE4}
